const suggestionArray = [
  "how to become a developper",
  "how to become a front_end developper",
  "how to become a back_end developper",
  "how to become a fullstack developper",
  "how to become a programmer",
  "Become a youtuber",
  "Become a fronted Python",
  "Become a fronted JAVA",
  "Become a fronted React",
  "Learn HTML & CSS",
  "Learn HTML & CSS & Javascript",
  "Learn React",
  "Learn Node.js",
  "Cyber Security Mentor",
  "Machine Learning",
  "Ingenier in UA/IA",
  "Mastering Javascript",
  "Developer",
  "Developement",
  "Programer",
  "Football",
  "Garde National",
  "Driver Taxie",
  "Tutorial",
  "Auto complete Search bar",
];
